### ISSUE TITLE
JWT.java has runtime exception unsolved

### ISSUE THREAD

**Issue by philipbabbage2016** [softtouchit/xjwt#1]
line 139
illegal key size

**Comment by haohe** [comment]
"On a default JDK installation, AES is limited to 128 bit key size. In order to perform 256-bit AES encryption, you will need to download and install Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy Files. Here are the steps to fix java.security.InvalidKeyException: Illegal key size exception:"  Please follow the suggestions here:

https://deveshsharmablogs.wordpress.com/2012/10/09/fixing-java-security-invalidkeyexception-illegal-key-size-exception/
